const supabase = require("../../config/supabase");
const { validateProduct } = require("../../validator/productValidator");

/**
 * POST create single product
 * Note: ID will be auto-generated by database trigger
 */
const createProduct = async (req, res) => {
  try {
    const productData = req.body;

    // Validate input
    const validation = validateProduct(productData);
    if (!validation.isValid) {
      return res.status(400).json({
        success: false,
        message: "Validation error",
        errors: validation.errors,
      });
    }

    // Remove id from productData if provided (will be auto-generated)
    const { id, ...dataToInsert } = productData;

    // Insert product
    const { data, error } = await supabase
      .from("products")
      .insert([dataToInsert])
      .select()
      .single();

    if (error) {
      return res.status(400).json({
        success: false,
        message: "Error creating product",
        error: error.message,
      });
    }

    res.status(201).json({
      success: true,
      message: "Product created successfully",
      data: data,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Internal server error",
      error: error.message,
    });
  }
};

/**
 * POST create multiple products (bulk insert)
 * Note: IDs will be auto-generated by database trigger
 */
const createMultipleProducts = async (req, res) => {
  try {
    const productsArray = req.body.products;

    if (!Array.isArray(productsArray) || productsArray.length === 0) {
      return res.status(400).json({
        success: false,
        message:
          "Request body must contain a 'products' array with at least one product",
      });
    }

    // Validate all products
    const validationErrors = [];
    const dataToInsert = [];

    productsArray.forEach((product, index) => {
      const validation = validateProduct(product);
      if (!validation.isValid) {
        validationErrors.push({
          index: index,
          errors: validation.errors,
        });
      } else {
        // Remove id if provided (will be auto-generated)
        const { id, ...productWithoutId } = product;
        dataToInsert.push(productWithoutId);
      }
    });

    if (validationErrors.length > 0) {
      return res.status(400).json({
        success: false,
        message: "Validation errors found",
        errors: validationErrors,
      });
    }

    // Insert all products
    const { data, error } = await supabase
      .from("products")
      .insert(dataToInsert)
      .select();

    if (error) {
      return res.status(400).json({
        success: false,
        message: "Error creating products",
        error: error.message,
      });
    }

    res.status(201).json({
      success: true,
      message: `${data.length} products created successfully`,
      count: data.length,
      data: data,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Internal server error",
      error: error.message,
    });
  }
};

module.exports = {
  createProduct,
  createMultipleProducts,
};
