// server/controllers/products/createProducts.js
const supabase = require("../../config/supabase");
const { validateProduct } = require("../../validator/productValidator");

const createProduct = async (req, res) => {
  try {
    console.log("=== CREATE PRODUCT START ===");
    console.log("Request body:", JSON.stringify(req.body, null, 2));

    const productData = req.body;

    // Remove id from productData if provided (will be auto-generated)
    const { id, ...dataToInsert } = productData;
    console.log(
      "Data to insert (after removing id):",
      JSON.stringify(dataToInsert, null, 2)
    );

    // Validate input (without id)
    const validation = validateProduct(dataToInsert);
    console.log("Validation result:", validation);

    if (!validation.isValid) {
      console.log("Validation failed:", validation.errors);
      return res.status(400).json({
        success: false,
        message: "Validation error",
        errors: validation.errors,
      });
    }

    // Insert product
    console.log("Attempting to insert into Supabase...");
    const { data, error } = await supabase
      .from("products")
      .insert([dataToInsert])
      .select()
      .single();

    if (error) {
      console.error("Supabase error:", error);
      return res.status(400).json({
        success: false,
        message: "Error creating product",
        error: error.message,
        details: error,
      });
    }

    console.log("Product created successfully:", data);
    console.log("=== CREATE PRODUCT END ===");

    res.status(201).json({
      success: true,
      message: "Product created successfully",
      data: data,
    });
  } catch (error) {
    console.error("=== CREATE PRODUCT ERROR ===");
    console.error("Error details:", error);
    console.error("Error stack:", error.stack);

    res.status(500).json({
      success: false,
      message: "Internal server error",
      error: error.message,
    });
  }
};

/**
 * POST create multiple products (bulk insert)
 * Note: IDs will be auto-generated by database trigger
 */
const createMultipleProducts = async (req, res) => {
  try {
    console.log("=== CREATE MULTIPLE PRODUCTS START ===");
    console.log("Request body:", JSON.stringify(req.body, null, 2));

    const productsArray = req.body.products;

    if (!Array.isArray(productsArray) || productsArray.length === 0) {
      console.log("Invalid products array");
      return res.status(400).json({
        success: false,
        message:
          "Request body must contain a 'products' array with at least one product",
      });
    }

    console.log(`Validating ${productsArray.length} products...`);

    // Validate all products
    const validationErrors = [];
    const dataToInsert = [];

    productsArray.forEach((product, index) => {
      // Remove id if provided (will be auto-generated)
      const { id, ...productWithoutId } = product;

      const validation = validateProduct(productWithoutId);
      if (!validation.isValid) {
        console.log(
          `Validation failed for product at index ${index}:`,
          validation.errors
        );
        validationErrors.push({
          index: index,
          errors: validation.errors,
        });
      } else {
        dataToInsert.push(productWithoutId);
      }
    });

    if (validationErrors.length > 0) {
      console.log("Validation errors found:", validationErrors);
      return res.status(400).json({
        success: false,
        message: "Validation errors found",
        errors: validationErrors,
      });
    }

    console.log(
      `All products valid. Inserting ${dataToInsert.length} products...`
    );
    console.log("Data to insert:", JSON.stringify(dataToInsert, null, 2));

    // Insert all products
    const { data, error } = await supabase
      .from("products")
      .insert(dataToInsert)
      .select();

    if (error) {
      console.error("Supabase error:", error);
      return res.status(400).json({
        success: false,
        message: "Error creating products",
        error: error.message,
        details: error,
      });
    }

    console.log(`${data.length} products created successfully`);
    console.log("Created products:", data);
    console.log("=== CREATE MULTIPLE PRODUCTS END ===");

    res.status(201).json({
      success: true,
      message: `${data.length} products created successfully`,
      count: data.length,
      data: data,
    });
  } catch (error) {
    console.error("=== CREATE MULTIPLE PRODUCTS ERROR ===");
    console.error("Error details:", error);
    console.error("Error stack:", error.stack);

    res.status(500).json({
      success: false,
      message: "Internal server error",
      error: error.message,
    });
  }
};

module.exports = {
  createProduct,
  createMultipleProducts,
};
