// server/validators/productValidator.js

/**
 * Validate product data for creation
 * Note: ID is NOT required here (will be auto-generated by database)
 * Schema matches database: id, name, category, price, image, description, link
 */
const validateProduct = (product) => {
  const errors = [];

  // Required fields (matching database schema)
  if (
    !product.name ||
    typeof product.name !== "string" ||
    product.name.trim() === ""
  ) {
    errors.push("Product name is required and must be a non-empty string");
  }

  if (product.price === undefined || product.price === null) {
    errors.push("Product price is required");
  } else if (typeof product.price !== "number" || product.price < 0) {
    errors.push("Product price must be a non-negative number");
  }

  if (
    !product.category ||
    typeof product.category !== "string" ||
    product.category.trim() === ""
  ) {
    errors.push("Product category is required and must be a non-empty string");
  }

  if (
    !product.link ||
    typeof product.link !== "string" ||
    product.link.trim() === ""
  ) {
    errors.push("Product link is required and must be a non-empty string");
  }

  // Optional fields validation (matching database schema)
  if (
    product.description !== undefined &&
    product.description !== null &&
    typeof product.description !== "string"
  ) {
    errors.push("Product description must be a string");
  }

  if (
    product.image !== undefined &&
    product.image !== null &&
    typeof product.image !== "string"
  ) {
    errors.push("Product image must be a string");
  }

  // Warn about fields that don't exist in database
  const validFields = [
    "id",
    "name",
    "category",
    "price",
    "image",
    "description",
    "link",
  ];
  const providedFields = Object.keys(product);
  const invalidFields = providedFields.filter(
    (field) => !validFields.includes(field)
  );

  if (invalidFields.length > 0) {
    errors.push(
      `Invalid fields: ${invalidFields.join(
        ", "
      )}. Valid fields are: ${validFields.join(", ")}`
    );
  }

  return {
    isValid: errors.length === 0,
    errors: errors,
  };
};

/**
 * Validate product data for update (partial update allowed)
 */
const validateProductUpdate = (updateData) => {
  const errors = [];

  // Check if at least one field is being updated
  if (Object.keys(updateData).length === 0) {
    errors.push("At least one field must be provided for update");
    return {
      isValid: false,
      errors: errors,
    };
  }

  // ID cannot be updated
  if (updateData.id !== undefined) {
    errors.push("Product ID cannot be updated");
  }

  // Validate only the fields that are present
  if (updateData.name !== undefined) {
    if (typeof updateData.name !== "string" || updateData.name.trim() === "") {
      errors.push("Product name must be a non-empty string");
    }
  }

  if (updateData.price !== undefined) {
    if (typeof updateData.price !== "number" || updateData.price < 0) {
      errors.push("Product price must be a non-negative number");
    }
  }

  if (updateData.category !== undefined) {
    if (
      typeof updateData.category !== "string" ||
      updateData.category.trim() === ""
    ) {
      errors.push("Product category must be a non-empty string");
    }
  }

  if (updateData.link !== undefined) {
    if (typeof updateData.link !== "string" || updateData.link.trim() === "") {
      errors.push("Product link must be a non-empty string");
    }
  }

  if (
    updateData.description !== undefined &&
    updateData.description !== null &&
    typeof updateData.description !== "string"
  ) {
    errors.push("Product description must be a string");
  }

  if (
    updateData.image !== undefined &&
    updateData.image !== null &&
    typeof updateData.image !== "string"
  ) {
    errors.push("Product image must be a string");
  }

  // Warn about fields that don't exist in database
  const validFields = [
    "name",
    "category",
    "price",
    "image",
    "description",
    "link",
  ];
  const providedFields = Object.keys(updateData);
  const invalidFields = providedFields.filter(
    (field) => !validFields.includes(field)
  );

  if (invalidFields.length > 0) {
    errors.push(
      `Invalid fields for update: ${invalidFields.join(
        ", "
      )}. Valid fields are: ${validFields.join(", ")}`
    );
  }

  return {
    isValid: errors.length === 0,
    errors: errors,
  };
};

module.exports = {
  validateProduct,
  validateProductUpdate,
};
